require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/crews", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Crew. As you add validations to Crew, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Crew.create! valid_attributes
      get crews_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      crew = Crew.create! valid_attributes
      get crew_url(crew)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_crew_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      crew = Crew.create! valid_attributes
      get edit_crew_url(crew)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Crew" do
        expect {
          post crews_url, params: { crew: valid_attributes }
        }.to change(Crew, :count).by(1)
      end

      it "redirects to the created crew" do
        post crews_url, params: { crew: valid_attributes }
        expect(response).to redirect_to(crew_url(Crew.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Crew" do
        expect {
          post crews_url, params: { crew: invalid_attributes }
        }.to change(Crew, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post crews_url, params: { crew: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested crew" do
        crew = Crew.create! valid_attributes
        patch crew_url(crew), params: { crew: new_attributes }
        crew.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the crew" do
        crew = Crew.create! valid_attributes
        patch crew_url(crew), params: { crew: new_attributes }
        crew.reload
        expect(response).to redirect_to(crew_url(crew))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        crew = Crew.create! valid_attributes
        patch crew_url(crew), params: { crew: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested crew" do
      crew = Crew.create! valid_attributes
      expect {
        delete crew_url(crew)
      }.to change(Crew, :count).by(-1)
    end

    it "redirects to the crews list" do
      crew = Crew.create! valid_attributes
      delete crew_url(crew)
      expect(response).to redirect_to(crews_url)
    end
  end
end
