require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/studios", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Studio. As you add validations to Studio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Studio.create! valid_attributes
      get studios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      studio = Studio.create! valid_attributes
      get studio_url(studio)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_studio_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      studio = Studio.create! valid_attributes
      get edit_studio_url(studio)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Studio" do
        expect {
          post studios_url, params: { studio: valid_attributes }
        }.to change(Studio, :count).by(1)
      end

      it "redirects to the created studio" do
        post studios_url, params: { studio: valid_attributes }
        expect(response).to redirect_to(studio_url(Studio.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Studio" do
        expect {
          post studios_url, params: { studio: invalid_attributes }
        }.to change(Studio, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post studios_url, params: { studio: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested studio" do
        studio = Studio.create! valid_attributes
        patch studio_url(studio), params: { studio: new_attributes }
        studio.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the studio" do
        studio = Studio.create! valid_attributes
        patch studio_url(studio), params: { studio: new_attributes }
        studio.reload
        expect(response).to redirect_to(studio_url(studio))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        studio = Studio.create! valid_attributes
        patch studio_url(studio), params: { studio: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested studio" do
      studio = Studio.create! valid_attributes
      expect {
        delete studio_url(studio)
      }.to change(Studio, :count).by(-1)
    end

    it "redirects to the studios list" do
      studio = Studio.create! valid_attributes
      delete studio_url(studio)
      expect(response).to redirect_to(studios_url)
    end
  end
end
